// Generated by gencpp from file my_example_pkg/my_servicesRequest.msg
// DO NOT EDIT!


#ifndef MY_EXAMPLE_PKG_MESSAGE_MY_SERVICESREQUEST_H
#define MY_EXAMPLE_PKG_MESSAGE_MY_SERVICESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_example_pkg
{
template <class ContainerAllocator>
struct my_servicesRequest_
{
  typedef my_servicesRequest_<ContainerAllocator> Type;

  my_servicesRequest_()
    : number(0)  {
    }
  my_servicesRequest_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct my_servicesRequest_

typedef ::my_example_pkg::my_servicesRequest_<std::allocator<void> > my_servicesRequest;

typedef boost::shared_ptr< ::my_example_pkg::my_servicesRequest > my_servicesRequestPtr;
typedef boost::shared_ptr< ::my_example_pkg::my_servicesRequest const> my_servicesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_example_pkg::my_servicesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_example_pkg::my_servicesRequest_<ContainerAllocator1> & lhs, const ::my_example_pkg::my_servicesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_example_pkg::my_servicesRequest_<ContainerAllocator1> & lhs, const ::my_example_pkg::my_servicesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_example_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2474488a3908093ec1307bdd5b35815e";
  }

  static const char* value(const ::my_example_pkg::my_servicesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2474488a3908093eULL;
  static const uint64_t static_value2 = 0xc1307bdd5b35815eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_example_pkg/my_servicesRequest";
  }

  static const char* value(const ::my_example_pkg::my_servicesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#First parameters above the line will be request and second one will be return messages\n"
"int32 number\n"
;
  }

  static const char* value(const ::my_example_pkg::my_servicesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_servicesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_example_pkg::my_servicesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_example_pkg::my_servicesRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_EXAMPLE_PKG_MESSAGE_MY_SERVICESREQUEST_H
