// Generated by gencpp from file my_example_pkg/my_services.msg
// DO NOT EDIT!


#ifndef MY_EXAMPLE_PKG_MESSAGE_MY_SERVICES_H
#define MY_EXAMPLE_PKG_MESSAGE_MY_SERVICES_H

#include <ros/service_traits.h>


#include <my_example_pkg/my_servicesRequest.h>
#include <my_example_pkg/my_servicesResponse.h>


namespace my_example_pkg
{

struct my_services
{

typedef my_servicesRequest Request;
typedef my_servicesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct my_services
} // namespace my_example_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_example_pkg::my_services > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::my_example_pkg::my_services&) { return value(); }
};

template<>
struct DataType< ::my_example_pkg::my_services > {
  static const char* value()
  {
    return "my_example_pkg/my_services";
  }

  static const char* value(const ::my_example_pkg::my_services&) { return value(); }
};


// service_traits::MD5Sum< ::my_example_pkg::my_servicesRequest> should match
// service_traits::MD5Sum< ::my_example_pkg::my_services >
template<>
struct MD5Sum< ::my_example_pkg::my_servicesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_example_pkg::my_services >::value();
  }
  static const char* value(const ::my_example_pkg::my_servicesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_example_pkg::my_servicesRequest> should match
// service_traits::DataType< ::my_example_pkg::my_services >
template<>
struct DataType< ::my_example_pkg::my_servicesRequest>
{
  static const char* value()
  {
    return DataType< ::my_example_pkg::my_services >::value();
  }
  static const char* value(const ::my_example_pkg::my_servicesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_example_pkg::my_servicesResponse> should match
// service_traits::MD5Sum< ::my_example_pkg::my_services >
template<>
struct MD5Sum< ::my_example_pkg::my_servicesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_example_pkg::my_services >::value();
  }
  static const char* value(const ::my_example_pkg::my_servicesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_example_pkg::my_servicesResponse> should match
// service_traits::DataType< ::my_example_pkg::my_services >
template<>
struct DataType< ::my_example_pkg::my_servicesResponse>
{
  static const char* value()
  {
    return DataType< ::my_example_pkg::my_services >::value();
  }
  static const char* value(const ::my_example_pkg::my_servicesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_EXAMPLE_PKG_MESSAGE_MY_SERVICES_H
